
GET http://127.0.0.1:5000/produtos


POST http://127.0.0.1:5000/produtos
Content-Type: application/json

{
    "nome": "Headset USB",
    "preco": 180.00
}


POST http://127.0.0.1:5000/produtos
Content-Type: application/json

{
    "nome": "Webcam HD"
}
